spring:
  profiles: 
    active: local
  jpa:
    show-sql: true
    databse-platform: org.hibernate.dialect.MySQLDialect
cloud:
  aws: 
    region:
      static: ${region:}
    credentials:
      accessKey: ${accessKey:}
      secretKey: ${secretKey:}
aws:
  database: 
    name: rds_mysql_db
    identifier: spring-aws-rds-sp1
    password: Qwerty12345
  s3: 
    bucket-name: spring_aws_s3_sp1