spring:
  profiles: 
    active: local
  jpa:
    show-sql: true
    databse-platform: org.hibernate.dialect.MySQLDialect
cloud:
  aws: 
    region:
      static: ${region:}
    credentials:
      accessKey: ${accessKey:}
      secretKey: ${secretKey:}
aws:
  database: 
    name: rds_mysql_db
    identifier: spring-aws-rds-sp1
    password: ${rdspwd:}
  s3: 
    bucket-name: spring-aws-s3-sp1/spring-aws
  sqs:
    queue-name: spring-aws-sqs-sp1
  whitelist:
    emails: 
      - phamhoanglinh137@gmail.com
    phones: 
      - 6594262264
    