logging:
  config: classpath:log4j2.xml
spring:
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/sp_group_db
    username: sp_group
    password: sp_group_pwd
  jpa:
    show-sql: true
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQLDialect