logging:
  config: classpath:log4j2.xml
spring:
  datasource: 
    url: jdbc:mysql://database:3306/sp_group_db
    username: sp_group
    password: sp_group_pwd
    continue-on-error: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0
  jpa:
    show-sql: true
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQLDialect
        default_schema: sp_db