version: "2.1"

services:
  db:
    image: sp_db_img
    container_name: sp_db
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "sp_group_db"
      MYSQL_USER: "sp_group"
      MYSQL_PASSWORD: "sp_group_pwd"
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW SCHEMAS;\""
      interval: 3s
      timeout: 1s
      retries: 5
  app:
    image: sp_app_img
    links:
      - db
    container_name: sp_app
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/deploy:/sp_group/deploy
    ports:
      - 8090:8080
